//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM_CS3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietSP()
        {
            this.HoaDonChiTiet = new HashSet<HoaDonChiTiet>();
            this.GioHangChiTiet = new HashSet<GioHangChiTiet>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdSP { get; set; }
        public Nullable<System.Guid> IdNsx { get; set; }
        public Nullable<System.Guid> IdMauSac { get; set; }
        public Nullable<System.Guid> IdDongSP { get; set; }
        public Nullable<int> NamBH { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
    
        public virtual DongSP DongSP { get; set; }
        public virtual MauSac MauSac { get; set; }
        public virtual NSX NSX { get; set; }
        public virtual SanPham SanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonChiTiet> HoaDonChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHangChiTiet> GioHangChiTiet { get; set; }
    }
}
